name: 'Linkage Monitor'
description: 'Checks the compatibility of the library with the latest Libraries BOM'
runs:
  using: "composite"
  steps:
    - name: Build Linkage Monitor
      run: ./mvnw -q -B -V install -pl dependencies,linkage-monitor -Dmaven.test.skip -Dinvoker.skip
      shell: bash
      working-directory: ${{ github.action_path }}/..
    - run: ${{ github.action_path }}/linkage-monitor.sh
      shell: bash
