name: 'Linkage Monitor'
description: 'Checks the compatibility of the library with the latest Libraries BOM'
runs:
  using: "composite"
  steps: 
    - id: download-linkage-monitor
      # We'll need to specify a version when downloading Linkage Monitor
      run: >
        curl --output /tmp/linkage-monitor-latest-all-deps.jar \
        "https://storage.googleapis.com/cloud-opensource-java-linkage-monitor/linkage-monitor-latest-all-deps.jar"
      shell: bash
    - run: ${{ github.action_path }}/linkage-monitor.sh
      shell: bash
